version: 1.0.{build}
clone_depth: 1
clone_folder: c:\gopath\src\www.velocidex.com\golang\velociraptor

environment:
  GOPATH: c:\gopath
  PATH: C:\msys64\mingw64\bin;%GOPATH%\bin;%PATH%
  VELOCIRAPTOR_CONFIG: artifacts\testdata\windows\appveyor.config.yaml

cache:
  - c:\gopath\src\www.velocidex.com\golang\velociraptor\vendor -> Gopkg.lock
  - c:\gopath\src\github.com -> Gopkg.lock

install:
- cmd: |
    echo %PATH%
    echo %GOPATH%
    mklink c:\Users\link c:\Windows
    go version
    go env

build_script:
- cmd: |
    regedit /S artifacts/testdata/windows/init.reg
    go get github.com/magefile/mage/mage
    go run make.go -v appveyor

test_script:
- cmd: output\velociraptor.exe golden artifacts\testdata\windows\
- cmd: output\velociraptor.exe golden artifacts\testdata\server\testcases\ --env srcDir=c:\gopath\src\www.velocidex.com\golang\velociraptor
- cmd: go test ./...

on_finish:
  - ps: Get-ChildItem artifacts/testdata/windows/*.out.yaml | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem artifacts/testdata/server/testcases/*.out.yaml | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
