version: 1.0.{build}
clone_depth: 1
clone_folder: c:\velociraptor
stack: Go 1.12

environment:
  GOPATH: c:\gopath
  PATH: C:\msys64\mingw64\bin;%GOPATH%\bin;%PATH%
  VELOCIRAPTOR_CONFIG: artifacts\testdata\windows\appveyor.config.yaml
  GOPROXY: https://proxy.golang.org
  GOCACHE: C:\Users\appveyor\AppData\Local\go-build

cache:
  - '%LocalAppData%\go-build -> .appveyor_cache_clear'
  - '%GOPATH%/pkg -> .appveyor_cache_clear'
  - 'gui/static/node_modules -> .appveyor_cache_clear'
  - 'gui/static/dist -> .appveyor_cache_clear'

install:
- cmd: |
    echo %PATH%
    echo %GOPATH%
    mklink c:\Users\link c:\Windows
    mkdir "C:\Program Files\Velociraptor"
    mkdir c:\tmp
    echo Hello > C:\hello.txt
    echo HelloADS > C:\hello.txt:myads
    fsutil file setshortname C:\hello.txt hi.txt
    echo "VSStest" > c:\Users\test.txt
    echo "VSStest2" > c:\Users\test2.txt
    sc.exe create TestingDetection1 binPath="%COMSPEC% /Q /c echo 'COMSPEC testing 1"
    ver
    vssadmin create shadow /for=c:
    wevtutil.exe cl System
    echo "VSStest2" >> c:\Users\test2.txt
    sc.exe create TestingDetection2 binPath="%COMSPEC% /Q /c echo 'COMSPEC testing 2"
    vssadmin create shadow /for=c:
    

- go version
- go env
- set GO111MODULE=on
- go mod download
- go mod verify
- ps: Install-Product node 11.14 x64
- npm root -g

build_script:
- set GO111MODULE=on
- cmd: |
    regedit /S artifacts/testdata/windows/init.reg
    go get github.com/magefile/mage/mage
    go run make.go -v appveyor

test_script:
- set GO111MODULE=on
- cmd: c:\velociraptor\output\velociraptor.exe golden -v --config c:\velociraptor\artifacts\testdata\windows\appveyor.config.yaml c:\velociraptor\artifacts\testdata\windows\ --env srcDir=c:\velociraptor
- cmd: c:\velociraptor\output\velociraptor.exe golden -v --config c:\velociraptor\artifacts\testdata\windows\appveyor.config.yaml c:\velociraptor\artifacts\testdata\server\testcases\ --env srcDir=c:\velociraptor
- cmd: go test ./...

on_finish:
  - ps: Get-ChildItem artifacts/testdata/windows/*.out.yaml | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem artifacts/testdata/server/testcases/*.out.yaml | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem output/velociraptor.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem output/velociraptor-linux.elf | % { Push-AppveyorArtifact $_.FullName -FileName "velociraptor-linux.elf" }
