CA.certificate: '-----BEGIN CERTIFICATE-----

  MIIC2zCCAcOgAwIBAgIBATANBgkqhkiG9w0BAQsFADAgMREwDwYDVQQDDAhncnJf

  dGVzdDELMAkGA1UEBhMCVVMwHhcNMTgwNDEzMTQxNDQ0WhcNMjgwNDExMTQxNDQ0

  WjAOMQwwCgYDVQQDDANncnIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB

  AQDcSW28V3Hq/81TqUHgjStitTUPQbP+EV2XXhyjeZZDJ2kWVO1PsUT7+IrmfTnF

  BBGVPViEytKobna+X1yh6X01iS7G2c6Sn0U+WofSnUyZI7FxToHrsKHxs2i7U/er

  lION6JvKoVKX0BCbWs67XbQMwB6/8V+D9MQjuQkbR1olPAuSicPFOvgTWvCf93K5

  kg0GbZXqGpgqR830eHT2d4D87P0kswuEF0FC4XxZSbl3N9XobMeJ0I5K4WuREMuU

  QWmIo2Ceyr7HvhozOgwN9tgtab5TvjHSis5/m6/5l0DNXcPGWSJnGAumzJ31QanV

  bMxMP85OfV6zaRtTm7ZzvzT7AgMBAAGjMjAwMA8GA1UdEwEB/wQFMAMBAf8wHQYD

  VR0OBBYEFOAJGWmAH3see/tB8yKaVz1xQv1sMA0GCSqGSIb3DQEBCwUAA4IBAQAH

  Q7emL6VCGqYg7jY05ms5bjrycAgb5azXFfy+Qm0iQOTTowgaqqylSKrZNDA+F4FT

  TS/xZePzWpO1/xRncsg/FDPT1kuzUCsiP3aOxm5R+MPo/sR2bJcFa9Gr+I/LNuiZ

  xgVVk/BJbEicnzFnmyHKtATAyC8bCYhngWrkraMoN/gDvVTiPUzYSW0/p/b/74Kz

  unYmefJq8qMi0PJzXzKbRSjioKETpODT9Eei5ni3p76LpHcGMuAvAHBqsYbbt0Bl

  hUft0UdHLxPqi0jBmIhKi8Q1CGOyvIXIRwA/W7zEd1nPI4z9tQuNKdqI50VH5Mih

  ItgybIt5e3PhIGaoCPR6

  -----END CERTIFICATE-----'
Client.server_urls: http://localhost:8080/
Client.private_key: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAxuvw3T61UDhM6DzWGPDZ7/ER/sZOFjDwNXVX3pDqMKagjot9

  NspSKWf38pjF6b8La+hvFC8SJ6oMy1f3569uaoBZlEFzUaCK8crxQJ35NcgOmlzJ

  4a9Q1Eagy2pw2Cmj7a3roN3zAXI3TVYGDySLV3hb+iFP44VmxFN+CYXLIOSNlQSE

  5du2CRoEhgMSWjwwbbdL7MSjAThBrNDQ/HjugzTs5KYy23OBXuEVIriQbjtFS3yw

  rY5k2jYh6jxVyJKXXve3iTOuVuiLXfVnZHTpPED7/2ujfdr9SgD8BWJeTN9a+eRi

  ZQZKsQo7WsXLcvA64BbIUZG5+7tknTMWFD16vQIDAQABAoIBAAo5Bd/Y4SiGPC2T

  Ms2FUy3pjasyNcEeMroMlb9yYxas+YNZ182BCEfod+2XvFQO5V9eSpcW9C/lpVKt

  6qeVdG80uWXNF0gSoBFdBJj1hWEmLtnv+tAGWnkOSCUsCzCQs0P7tChIP7zLSdxH

  l3gfwKl2HgP0wk5HBMkCIXAL2CyQeyRcmKqERvDULKjlrHNxIdGb7huAZbSWpD33

  y7T54apQROZAPcULj5DDyUJ6fwxSnd9Fg+w+avbBPbNwWISLDFpopWzlsuHgsyx0

  A4J7QUtczGsHfaEpZTxCxrSeaAEoJvdzWse/YHbRdn7eU4bbmKW9S/ajwCbnh8gp

  e9ZzsQECgYEA4tb7GfFdHAr5diQOWtZxQwREHMhW/SqFhFnY9PtSmSGRzDxmJXBO

  UDL3A766xD6Z20/Y3vJWIkn+rOiZz7dn2hQumQiTJI0yH5lLmhELd/cvkfAUgDqc

  6KtnzWbaElwVug0AWmHHx5n+c77cufz9tSqpWqbxiNNFBeD/e2J4HNUCgYEA4H41

  bNjBYQ2zSxvZjhSy0AQShYhENPc0MlUX9cn/hRm8ugE/I4P5qxDne1PlW8ghjRuc

  R5B5/hDPIysh6z6AaPZ9uvb25tsTEpjxjs7x+PnPwj55I9I258zPrvgjnNkPjEfs

  +52IEruwKheXZ2naPKNXaICws7FNupP47MohOkkCgYAwwjMRPX9dEsLScSegwO1x

  kU4uvaVtH6G5dDKdXhRAFCYpt2XhcEV1Ga9c37d3jVk2+e/M5Fw9XJhghFLjgjHR

  f3sQq/Ys6ii3ABVvFXDYpYpVHTza3z5xCL70OMJxJdgJuNe1lcUCk4hNSt5ZIBdM

  xNHISZArb/YrMFTaKa1VzQKBgDLFmIOjiijPFmu4Qr3VhJNzOFUm+nYYKp/vitm1

  86pApeRTf9oicQb1bcUAtnDJlHz7b57n2A9T8eT8TlGL8zLJ/KmaTUDs7yVXndo0

  h5lNtmUyB+fIFU7bjWT/Dd7dYJzTb4+Ak1PZSwBaEY377LWmI5Co+k3JndDCwpub

  I2SxAoGAVFoSGzGGIMlLIzzrzts09IcpsFWyx3gG9UUKIuYLP/Qo9Ps0MOL6qXq3

  SxecJK/L/zQTxtyO6GEyB90LRRxnbWE4Ai+G6FnPXzTYyF2pOuLV9g3BSoKyyeAC

  eeOklyZabh8qEBYkQKgcMDsFubHJVn6xnn6zGOyj1h5CSoD1nGY=

  -----END RSA PRIVATE KEY-----

  '
